# Generated by Django 4.1.4 on 2023-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
