# Generated by Django 4.1.4 on 2023-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
