# Generated by Django 4.1.4 on 2023-08-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_lecture_end_time_alter_lecture_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.class'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.subject'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.teacher'),
        ),
    ]
