# Generated by Django 4.1.4 on 2023-08-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_lecture_class_id_alter_lecture_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
